services:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ../deployments/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
    - ../deployments/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - prometheus-data:/prometheus
    ports:
    - "9090:9090"

  agent:
    build:
      context: ..
      dockerfile: deployments/Dockerfile

    container_name: mikrotik-defender

    restart: unless-stopped

    volumes:
      - ../configs/config.yml:/app/configs/config.yml:ro
      - defender-data:/app/data

    environment:
      - TZ=Europe/Warsaw
      - MIKROTIK_PASSWORD=${MIKROTIK_PASSWORD}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  defender-data:
  prometheus-data:
  grafana-data:

